/**
 * SanGuoPai Parameterized Test Harness
 *
 * A variant of harness.js that accepts modified game data (enemies, generals, rules)
 * generated by the tuner. This allows testing how parameter changes affect game balance.
 *
 * Usage:
 *   import { runBatchWithParams } from './harness_params.js';
 *   import { applyParams } from './game_params.js';
 *   const gameData = applyParams(params);
 *   const results = runBatchWithParams(decideFn, gameData, { runs: 100 });
 */

import { Deck, Hand, Card } from '../../js/engine/blackjack.js';
import AIEngine from '../../js/engine/ai.js';
import CombatEngine from '../../js/engine/combat.js';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Pre-load original game data (fallback when no custom data provided)
const defaultGeneralsData = JSON.parse(readFileSync(join(__dirname, '../../public/data/generals.json'), 'utf-8'));
const defaultEnemiesData  = JSON.parse(readFileSync(join(__dirname, '../../public/data/enemies.json'),  'utf-8'));
const defaultSchemesData  = JSON.parse(readFileSync(join(__dirname, '../../public/data/schemes.json'),  'utf-8'));
const defaultRelicsData   = JSON.parse(readFileSync(join(__dirname, '../../public/data/relics.json'),   'utf-8'));

// ---------------------------------------------------------------------------
// Single Game Runner (with custom game data)
// ---------------------------------------------------------------------------

export function runSingleGameWithParams(decideFn, gameData, options = {}) {
  const {
    difficulty = '標準',
    maxStages = 99,
    seed = null,
    verbose = false,
  } = options;

  // -- extract custom or default data ----------------------------------------
  const allGenerals = gameData?.generals ?? defaultGeneralsData.generals;
  const allEnemies  = gameData?.enemies  ?? defaultEnemiesData.enemies;
  const allSchemes  = gameData?.schemes  ?? (defaultSchemesData.schemes || []);
  const allRelics   = gameData?.relics   ?? (defaultRelicsData.relics || []);
  const rules       = gameData?.rules    ?? {};

  // -- seedable RNG ----------------------------------------------------------
  let rngState = seed ?? Math.floor(Math.random() * 2147483647);
  function random() {
    rngState = (rngState * 16807) % 2147483647;
    return (rngState - 1) / 2147483646;
  }

  // -- game state ------------------------------------------------------------
  let money = 0;
  let selectedGenerals = [];
  let schemes = [];
  let relics = [];
  let defeatedEnemies = [];
  let maxSlots = rules.maxSlots ?? 5;
  let currentStageIndex = 1;
  let totalRoundsPlayed = 0;
  let totalHandsPlayed = 0;
  let totalMoneyEarned = 0;
  let gameLog = [];

  function log(msg) {
    if (verbose) console.log(msg);
    gameLog.push(msg);
  }

  // -- difficulty & rules modifiers ------------------------------------------
  function getDifficultyMultiplier() {
    if (difficulty === '入門') return rules.easyMultiplier ?? 0.85;
    if (difficulty === '困難') return rules.hardMultiplier ?? 1.15;
    return 1.0;
  }

  function getAIThresholdModifier() {
    if (difficulty === '困難') return -(rules.hardAIPenalty ?? 0.25) * 4;
    if (difficulty === '入門') return 1;
    return 0;
  }

  const handsPerBattle = rules.handsPerBattle ?? 3;
  const discardsPerBattle = rules.discardsPerBattle ?? 3;
  const hitLimitGlobal = rules.hitLimit ?? 3;
  const initialGenerals = rules.initialGenerals ?? 3;

  // -- initial loadout -------------------------------------------------------
  const shuffledGenerals = [...allGenerals].sort(() => random() - 0.5);
  selectedGenerals = shuffledGenerals.slice(0, initialGenerals);

  // -- battle loop -----------------------------------------------------------
  let stagesCleared = 0;
  let battleLost = false;

  while (currentStageIndex <= maxStages && !battleLost) {
    const enemy = allEnemies.find(e => e.stage_index === currentStageIndex);
    if (!enemy) break;

    const moneyTarget = Math.floor(enemy.money_target * getDifficultyMultiplier());
    const maxRounds = enemy.max_rounds;
    let battleMoney = 0;
    let currentRound = 0;

    // Per-battle resources
    let hands = handsPerBattle;
    const bonusHands = selectedGenerals.reduce((sum, g) => sum + (g.bonus_hands || 0), 0);
    hands += bonusHands;
    const fCounts = selectedGenerals.reduce((acc, g) => {
      if (g.faction) acc[g.faction] = (acc[g.faction] || 0) + 1;
      return acc;
    }, {});
    const weiBonus = fCounts['魏'] >= 3 ? 1 : 0;
    const bonusDiscards = selectedGenerals.reduce((sum, g) => sum + (g.bonus_discards || 0), 0);
    let discards = discardsPerBattle + bonusDiscards + weiBonus;

    log(`=== Stage ${currentStageIndex}: ${enemy.name} (target: ${moneyTarget}) ===`);

    // -- round loop ------------------------------------------------------------
    while (currentRound < maxRounds && battleMoney < moneyTarget && hands > 0) {
      currentRound++;
      totalRoundsPlayed++;

      const deck = new Deck();
      for (let i = deck.cards.length - 1; i > 0; i--) {
        const j = Math.floor(random() * (i + 1));
        [deck.cards[i], deck.cards[j]] = [deck.cards[j], deck.cards[i]];
      }

      let playerHands = [new Hand()];
      let currentHandIndex = 0;
      let enemyHand = new Hand();
      let hitsThisRound = 0;
      const bonusHitLimit = selectedGenerals.reduce((sum, g) => sum + (g.hit_limit_bonus || 0), 0);
      let hitLimit = hitLimitGlobal + bonusHitLimit;
      let turn = 'PLAYER';
      let selectedForDiscard = new Set();
      let guanPingActive = false;
      let ganNingActive = false;
      let zhugeLiangActive = false;
      let firstHitDone = false;
      let bustThisRound = false;
      let xiahouDunBuffActive = false;
      let xiahouDunBuffPending = false;
      let enemyForceStand = false;
      let schemesUsedThisRound = false;
      let drewAceThisRound = false;

      selectedGenerals.forEach(g => {
        if (g.id === 'zhu_ge_liang' && g.skill_trigger === '回合開始時') {
          zhugeLiangActive = true;
        }
      });

      playerHands[0].addCard(deck.draw());
      playerHands[0].addCard(deck.draw());
      const extraDraw = selectedGenerals.reduce((sum, g) => sum + (g.extra_draw || 0), 0);
      for (let i = 0; i < extraDraw; i++) {
        playerHands[0].addCard(deck.draw());
      }
      enemyHand.addCard(deck.draw());
      enemyHand.addCard(deck.draw());

      log(`  Round ${currentRound}/${maxRounds}: dealt ${playerHands[0].getPoints()} vs enemy ${enemyHand.cards[0].toString()}`);

      // -- player turn loop ----------------------------------------------------
      let actionCount = 0;
      const MAX_ACTIONS_PER_ROUND = 50;
      while (turn === 'PLAYER' && hands > 0) {
        if (actionCount++ > MAX_ACTIONS_PER_ROUND) {
          log(`    FORCE END: too many actions`);
          hands--;
          totalHandsPlayed++;
          turn = 'ENEMY';
          break;
        }
        const hand = playerHands[currentHandIndex];

        const state = buildState({
          playerPoints: hand.getPoints(),
          playerCards: hand.cards,
          hitsThisRound,
          hitLimit,
          handsRemaining: hands,
          discardsRemaining: discards,
          selectedCardIndices: Array.from(selectedForDiscard),
          enemyVisibleCard: enemyHand.cards[0] || null,
          enemyPoints: enemyHand.getPoints(),
          enemyTendency: enemy.ai_tendency,
          enemyStandThreshold: enemy.ai_stand_threshold,
          battleMoney,
          moneyTarget,
          currentRound,
          maxRounds,
          money,
          difficulty,
          selectedGenerals,
          schemes,
          relics,
          maxSlots,
          canHit: hitsThisRound < hitLimit && !hand.isStand,
          canStand: !hand.isStand && playerHands.length === 1,
          canDoubleDown: hand.canDoubleDown(),
          canSplit: hand.canSplit(),
          canDiscard: discards > 0,
          roundsRemaining: maxRounds - currentRound,
          progressRatio: battleMoney / moneyTarget,
        });

        let decision;
        try {
          decision = decideFn(state);
        } catch (err) {
          log(`    Agent ERROR: ${err.message}`);
          decision = { action: 'STAND' };
        }

        if (!decision || !decision.action) {
          decision = { action: 'STAND' };
        }

        const action = decision.action;

        if (action === 'HIT' && hitsThisRound < hitLimit && !hand.isStand) {
          const card = deck.draw();
          hand.addCard(card);
          hitsThisRound++;
          if (card.rank === 'A') drewAceThisRound = true;
          selectedGenerals.forEach(g => {
            if (g.id === 'guan_ping' && card.rank === 'A') guanPingActive = true;
            if (g.id === 'gan_ning' && !firstHitDone) ganNingActive = true;
          });
          firstHitDone = true;
          log(`    HIT -> ${hand.getPoints()} (${card.toString()})`);

          if (hand.isBust()) {
            bustThisRound = true;
            log(`    BUST at ${hand.getPoints()}`);
            if (currentHandIndex < playerHands.length - 1) {
              currentHandIndex++;
              log(`    Switch to hand ${currentHandIndex + 1}`);
            } else {
              hands--;
              totalHandsPlayed++;
              turn = 'ENEMY';
            }
          }
        }
        else if (action === 'STAND' && !hand.isStand) {
          hand.stand();
          log(`    STAND at ${hand.getPoints()}`);
          if (currentHandIndex < playerHands.length - 1) {
            currentHandIndex++;
            log(`    Switch to hand ${currentHandIndex + 1}`);
          } else {
            hands--;
            totalHandsPlayed++;
            turn = 'ENEMY';
          }
        }
        else if (action === 'DOUBLE_DOWN' && hand.canDoubleDown()) {
          const card = deck.draw();
          hand.doubleDown(card);
          log(`    DOUBLE DOWN -> ${hand.getPoints()} (${card.toString()})`);
          hands--;
          totalHandsPlayed++;
          turn = 'ENEMY';
        }
        else if (action === 'SPLIT' && hand.canSplit()) {
          const card1 = hand.cards[0];
          const card2 = hand.cards[1];
          const h1 = new Hand();
          h1.addCard(card1);
          h1.addCard(deck.draw());
          const h2 = new Hand();
          h2.addCard(card2);
          h2.addCard(deck.draw());
          playerHands = [h1, h2];
          currentHandIndex = 0;
          selectedForDiscard.clear();
          log(`    SPLIT into ${h1.getPoints()} and ${h2.getPoints()}`);
        }
        else if (action === 'DISCARD' && discards > 0) {
          // Strategic discard: replace entire hand with 2 fresh cards
          hand.cards = [];
          for (let i = 0; i < 2; i++) {
            const newCard = deck.draw();
            hand.addCard(newCard);
          }
          hitsThisRound = 0; // reset hit count for the new hand
          firstHitDone = false;
          discards--;
          selectedForDiscard.clear();
          log(`    DISCARD + redraw -> ${hand.getPoints()} (fresh 2 cards)`);
        }
        else if (action === 'USE_SCHEME' && decision.schemeIndex != null) {
          const scheme = schemes[decision.schemeIndex];
          if (scheme) {
            schemesUsedThisRound = true;
            schemes.splice(decision.schemeIndex, 1);
            if (scheme.id === 'empty_city') enemyForceStand = true;
            log(`    USE SCHEME: ${scheme.name}`);
          }
        }
        else if (action === 'PLAY_HAND' && hands > 0) {
          if (!hand.isStand && !hand.isBust()) hand.stand();
          const allReady = playerHands.every(h => h.isStand || h.isBust());
          if (allReady) {
            hands--;
            totalHandsPlayed++;
            turn = 'ENEMY';
            log(`    PLAY HAND at ${hand.getPoints()}`);
          } else {
            while (currentHandIndex < playerHands.length - 1) {
              currentHandIndex++;
              if (!playerHands[currentHandIndex].isStand && !playerHands[currentHandIndex].isBust()) {
                break;
              }
            }
            const nowReady = playerHands.every(h => h.isStand || h.isBust());
            if (nowReady) {
              hands--;
              totalHandsPlayed++;
              turn = 'ENEMY';
            }
          }
        }
        else {
          if (!hand.isStand) {
            hand.stand();
            log(`    FALLBACK STAND at ${hand.getPoints()}`);
            if (currentHandIndex < playerHands.length - 1) {
              currentHandIndex++;
            } else {
              hands--;
              totalHandsPlayed++;
              turn = 'ENEMY';
            }
          } else {
            hands--;
            totalHandsPlayed++;
            turn = 'ENEMY';
          }
        }
      }

      // -- enemy turn ----------------------------------------------------------
      if (turn === 'ENEMY') {
        if (enemyForceStand) {
          log(`    Enemy forced stand (Empty City)`);
        } else {
          const diffMod = getAIThresholdModifier();
          const aiOffset = selectedGenerals.reduce((sum, g) => sum + (g.ai_threshold_offset || 0), 0);
          while (AIEngine.shouldHit(enemy, enemyHand, playerHands[0], diffMod + aiOffset)) {
            const card = deck.draw();
            enemyHand.addCard(card);
            if (enemyHand.isBust()) {
              log(`    Enemy BUST at ${enemyHand.getPoints()}`);
              const enemyBustBonus = selectedGenerals.reduce((sum, g) => sum + (g.enemy_bust_bonus || 0), 0);
              if (enemyBustBonus > 0) {
                battleMoney += enemyBustBonus;
                totalMoneyEarned += enemyBustBonus;
                log(`    Enemy bust bonus: +$${enemyBustBonus}`);
              }
              break;
            }
          }
        }

        // -- resolve ------------------------------------------------------------
        const ePoints = enemyHand.getPoints();
        let roundMoney = 0;

        for (let hi = 0; hi < playerHands.length; hi++) {
          const ph = playerHands[hi];
          const pp = ph.getPoints();

          const additive = [];
          const multipliers = [];

          // Bust protection from generals
          const bustProtection = selectedGenerals.reduce((sum, g) => sum + (g.bust_protection || 0), 0);

          if (hi === currentHandIndex) {
            if (guanPingActive && selectedGenerals.some(g => g.id === 'guan_ping')) {
              additive.push({ name: '關平', value: 75 });
            }
            if (ganNingActive && selectedGenerals.some(g => g.id === 'gan_ning')) {
              additive.push({ name: '甘寧', value: 90 });
            }
            if (zhugeLiangActive && !ph.isBust() && selectedGenerals.some(g => g.id === 'zhu_ge_liang')) {
              multipliers.push({ name: '諸葛亮', value: 2.2 });
            }
          }

          selectedGenerals.forEach(g => {
            const isSettlement = g.skill_trigger === '結算時';
            const is21Trigger = g.skill_trigger === '達成 21 點時' && pp === 21;
            const isXiahouBuff = g.skill_trigger === '爆牌時' && xiahouDunBuffActive;

            if (isSettlement || is21Trigger || isXiahouBuff) {
              let effectApplied = false;
              g.skill_effects.forEach(eff => {
                let shouldApply = false;
                const cond = eff.condition;

                if (!cond || cond === '該次結算' || cond === '無' || cond === '無條件') {
                  shouldApply = true;
                } else if (cond === '玩家點數恰為 21') {
                  shouldApply = pp === 21;
                } else if (cond === '否則') {
                  shouldApply = !effectApplied;
                } else if (cond === '玩家點數 ≥ 15') {
                  shouldApply = pp >= 15;
                } else if (cond === '玩家點數 ≥ 17 且 ≤ 20' || cond === '玩家點數為 17～20') {
                  shouldApply = pp >= 17 && pp <= 20;
                } else if (cond === '敵將點數 ≥ 17') {
                  shouldApply = ePoints >= 17;
                } else if (cond === '敵將點數 ≥ 18') {
                  shouldApply = ePoints >= 18;
                } else if (cond === '玩家要牌次數為 0' || cond === '玩家未要牌即直接出牌（僅初始兩張）') {
                  shouldApply = hitsThisRound === 0;
                } else if (cond === '玩家要牌次數為 1') {
                  shouldApply = hitsThisRound === 1;
                } else if (cond === '玩家要牌次數 ≤ 1') {
                  shouldApply = hitsThisRound <= 1;
                } else if (cond === '玩家手牌數為 2 張') {
                  shouldApply = ph.cards.length === 2;
                } else if (cond === '玩家手牌數 ≥ 4 張') {
                  shouldApply = ph.cards.length >= 4;
                } else if (cond === '玩家點數大於敵將且差 ≥ 3') {
                  shouldApply = pp > ePoints && (pp - ePoints) >= 3;
                } else if (cond === '玩家點數大於敵將且差 ≥ 5') {
                  shouldApply = pp > ePoints && (pp - ePoints) >= 5;
                } else if (cond === '玩家點數為 20 或 21') {
                  shouldApply = pp === 20 || pp === 21;
                } else if (cond === '手牌中至少 2 張同花色') {
                  const suits = {};
                  ph.cards.forEach(c => { suits[c.suit] = (suits[c.suit] || 0) + 1; });
                  shouldApply = Object.values(suits).some(count => count >= 2);
                } else if (cond === '手牌中有 3 張以上同花色') {
                  const suits = {};
                  ph.cards.forEach(c => { suits[c.suit] = (suits[c.suit] || 0) + 1; });
                  shouldApply = Object.values(suits).some(count => count >= 3);
                } else if (cond === '敵將明牌為 10 或 J/Q/K（視為 10）') {
                  const visibleRank = enemyHand.cards[0]?.rank;
                  shouldApply = visibleRank === '10' || ['J','Q','K'].includes(visibleRank);
                } else if (cond === '敵將明牌為 A') {
                  shouldApply = enemyHand.cards[0]?.rank === 'A';
                } else if (cond === '本回合要牌得到 A 則結算時額外加上') {
                  shouldApply = drewAceThisRound;
                } else if (cond === '本回合第一次要牌後結算時生效') {
                  shouldApply = firstHitDone && hitsThisRound >= 1;
                } else if (cond === '本回合曾觸發觀星且未爆牌，結算時') {
                  shouldApply = zhugeLiangActive && !ph.isBust();
                } else if (cond === '本回合使用過錦囊') {
                  shouldApply = schemesUsedThisRound;
                } else if (cond === '上一回合己方曾爆牌（風險回報）') {
                  shouldApply = false;
                } else if (cond === '下一回合結算時生效（僅下一場）') {
                  shouldApply = xiahouDunBuffActive;
                }

                if (shouldApply) {
                  effectApplied = true;
                  if (eff.type === '加法') additive.push({ name: g.skill_name, value: eff.value });
                  if (eff.type === '乘法') multipliers.push({ name: g.skill_name, value: eff.value });
                }
              });
            }
          });

          if (fCounts['吳'] >= 3) {
            const suits = {};
            ph.cards.forEach(c => { suits[c.suit] = (suits[c.suit] || 0) + 1; });
            if (Object.values(suits).some(c => c >= 3)) {
              multipliers.push({ name: '吳羈絆', value: 1.1 });
            }
          }

          const result = CombatEngine.calculateMoney(
            pp, ePoints, ph.isBlackjack(), ph.betMultiplier,
            additive.map(a => a.value),
            multipliers.map(m => m.value),
            bustProtection
          );

          if (result.money > 0) {
            let handMoney = result.money;
            if (ph.isBlackjack() && (rules.blackjackPayout ?? 1.5) > 1.0) {
              handMoney = Math.floor(handMoney * (rules.blackjackPayout ?? 1.5));
            }
            roundMoney += handMoney;
          }
        }

        battleMoney += roundMoney;
        totalMoneyEarned += roundMoney;
        log(`    Round result: +$${roundMoney} (total: ${battleMoney}/${moneyTarget})`);

        if (bustThisRound && fCounts['蜀'] >= 3) {
          const counter = 30 + (fCounts['蜀'] - 3) * 10;
          battleMoney += counter;
          totalMoneyEarned += counter;
        }

        if (difficulty === '困難' && bustThisRound && random() < (rules.hardAIPenalty ?? 0.25)) {
          const penalty = Math.floor(20 * 1.2);
          money = Math.max(0, money - penalty);
        }
      }
    }

    // -- battle resolution -----------------------------------------------------
    if (battleMoney >= moneyTarget) {
      stagesCleared++;
      defeatedEnemies.push(enemy.name);
      log(`  CLEARED stage ${currentStageIndex}!`);

      if (selectedGenerals.length < maxSlots) {
        const available = allGenerals.filter(g =>
          !selectedGenerals.find(sg => sg.id === g.id)
        );
        if (available.length > 0) {
          const pick = available[Math.floor(random() * available.length)];
          selectedGenerals.push(pick);
          log(`  Recruited: ${pick.name}`);
        }
      }
      currentStageIndex++;
    } else {
      log(`  LOST at stage ${currentStageIndex} (${battleMoney}/${moneyTarget})`);
      battleLost = true;
    }
  }

  // -- final score -----------------------------------------------------------
  const difficultyMultiplier = difficulty === '入門' ? 1.0 : difficulty === '標準' ? 2.0 : 3.5;
  let weightedScore = 0;
  for (let i = 1; i <= stagesCleared; i++) {
    weightedScore += i * difficultyMultiplier;
  }

  return {
    stagesCleared,
    weightedScore,
    finalStage: currentStageIndex,
    totalRoundsPlayed,
    totalHandsPlayed,
    totalMoneyEarned,
    finalMoney: money,
    generalsCount: selectedGenerals.length,
    defeatedEnemies: [...defeatedEnemies],
    log: verbose ? gameLog : undefined,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildState(overrides) {
  return {
    playerPoints: 0,
    playerCards: [],
    hitsThisRound: 0,
    hitLimit: 3,
    handsRemaining: 3,
    discardsRemaining: 3,
    selectedCardIndices: [],
    enemyVisibleCard: null,
    enemyPoints: 0,
    enemyTendency: '穩健',
    enemyStandThreshold: 17,
    battleMoney: 0,
    moneyTarget: 100,
    currentRound: 1,
    maxRounds: 3,
    money: 0,
    difficulty: '標準',
    selectedGenerals: [],
    schemes: [],
    relics: [],
    maxSlots: 5,
    canHit: false,
    canStand: false,
    canDoubleDown: false,
    canSplit: false,
    canDiscard: false,
    roundsRemaining: 2,
    progressRatio: 0,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Batch Runner (with custom game data)
// ---------------------------------------------------------------------------

export function runBatchWithParams(decideFn, gameData, options = {}) {
  const {
    runs = 100,
    difficulties = ['標準'],
    verbose = false,
  } = options;

  const results = [];
  let overall = {
    totalRuns: 0,
    totalWeightedScore: 0,
    maxStagesCleared: 0,
    stageDistribution: {},
  };

  for (const difficulty of difficulties) {
    for (let i = 0; i < runs; i++) {
      const result = runSingleGameWithParams(decideFn, gameData, { difficulty, verbose: verbose && i < 3 });
      results.push({ ...result, runIndex: i, difficulty });

      overall.totalRuns++;
      overall.totalWeightedScore += result.weightedScore;
      overall.maxStagesCleared = Math.max(overall.maxStagesCleared, result.stagesCleared);
      const key = `${difficulty}-${result.stagesCleared}`;
      overall.stageDistribution[key] = (overall.stageDistribution[key] || 0) + 1;
    }
  }

  const avgWeightedScore = overall.totalWeightedScore / overall.totalRuns;

  return {
    runs: results,
    summary: {
      totalRuns: overall.totalRuns,
      averageWeightedScore: avgWeightedScore,
      maxStagesCleared: overall.maxStagesCleared,
      stageDistribution: overall.stageDistribution,
      byDifficulty: difficulties.map(d => {
        const dRuns = results.filter(r => r.difficulty === d);
        return {
          difficulty: d,
          runs: dRuns.length,
          avgWeightedScore: dRuns.reduce((s, r) => s + r.weightedScore, 0) / dRuns.length,
          avgStagesCleared: dRuns.reduce((s, r) => s + r.stagesCleared, 0) / dRuns.length,
          maxStages: Math.max(...dRuns.map(r => r.stagesCleared)),
          stageDist: dRuns.reduce((acc, r) => {
            acc[r.stagesCleared] = (acc[r.stagesCleared] || 0) + 1;
            return acc;
          }, {}),
        };
      }),
    },
  };
}
